config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :articles, only: [:index, :show]
  
  namespace :admin do
    resources :articles

    root to: 'articles#index'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :description

  enum :status, [ :draft, :waiting_for_review, :published ]
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]

    # GET /admin/articles or /admin/articles.json
    def index
      @articles = Article.all
    end

    # GET /admin/articles/1 or /admin/articles/1.json
    def show
    end

    # GET /admin/articles/new
    def new
      @article = Article.new
    end

    # GET /admin/articles/1/edit
    def edit
    end

    # POST /admin/articles or /admin/articles.json
    def create
      @article = Article.new(article_params)

      respond_to do |format|
        if @article.save
          format.html { redirect_to [:admin, @article], notice: "Article was successfully created." }
          format.json { render :show, status: :created, location: [:admin, @article] }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/articles/1 or /admin/articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to [:admin, @article], notice: "Article was successfully updated." }
          format.json { render :show, status: :ok, location: [:admin, @article] }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/articles/1 or /admin/articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to admin_articles_path, status: :see_other, notice: "Article was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params.expect(:id))
      end

      # Only allow a list of trusted parameters through.
      def article_params
        params.expect(article: [ :title, :description, :summary, :cover_image ])
      end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.expect(article: [ :title, :description, :summary ])
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= article.summary %>
  </p>

</div>

app/views/admin/articles/_form.html.erb
<div class='p-2'>
  <%= form_with(model: [:admin, article]) do |form| %>
    <% if article.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
          <% article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, class: 'block'%>
      <%= form.text_field :title, class: 'border-1 w-full' %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.rich_text_area :description %>
    </div>

    <div>
      <%= form.label :summary, style: "display: block" %>
      <%= form.textarea :summary, class: 'border-1 w-full'%>
    </div>

    <div>
      <%= form.label :cover_image, style: "display: block" %>
      <%= form.file_field :cover_image %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/admin/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", [:admin, @article] %> |
  <%= link_to "Back to articles", admin_articles_path %>
</div>

app/views/admin/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Articles" %>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", [:admin, article] %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_admin_article_path %>

app/views/admin/articles/new.html.erb
<% content_for :title, "New article" %>

<h1>New article</h1>

<%= render "form", admin_article: @admin_article %>

<br>

<div>
  <%= link_to "Back to articles", admin_articles_path %>
</div>

app/views/admin/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_admin_article_path(@article) %> |
  <%= link_to "Back to articles", admin_articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>